server: 
  port: 9527
 
spring: 
  application:
    name: microservicecloud-zuul-gateway
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: gateway9527.com
    prefer-ip-address: true 

zuul:
  prefix: /hawking                                   #设置统一公共前缀
  #ignored-services: microservicecloud-dept           #防止用真实微服务地址访问
  ignored-services: "*"                               #忽略所有的微服务真实地址
  routes:
    mydept.serviceId: microservicecloud-dept          #真实微服务地址
    mydept.path: /mydept/**                           #虚拟地址
#微服务信息配置
info:
  app.name: hawking-microservicecloud
  company.name: www.hawking.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}

